spring:
  application:
    name: demo
  threads:
    virtual:
      enabled: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      probes:
        add-additional-paths: true
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true